basePath: /
definitions:
  controller.Antrian:
    properties:
      _id:
        type: string
      identitas_pasien:
        $ref: '#/definitions/controller.Pasien'
      nomor_antrian:
        type: integer
      poli:
        $ref: '#/definitions/controller.Poliklinik'
      status_antrian:
        description: Tanggal_Pendaftaran primitive.DateTime `bson:"tanggal_pendaftaran,omitempty"
          json:"tanggal_pendaftaran,omitempty"`
        type: string
    type: object
  controller.Dokter:
    properties:
      _id:
        type: string
      nama_dokter:
        type: string
      spesialisasi:
        type: string
    type: object
  controller.JamKerja:
    properties:
      durasi:
        example: 8
        type: integer
      gmt:
        example: 7
        type: integer
      hari:
        example:
        - Senin
        - Selasa
        - Rabu
        - Kamis
        - Jumat
        - Sabtu
        - Minggu
        items:
          type: string
        type: array
      jam_keluar:
        example: "16:00"
        type: string
      jam_masuk:
        example: "08:00"
        type: string
      piket_tim:
        example: Piket Z
        type: string
      shift:
        example: 2
        type: integer
    type: object
  controller.Karyawan:
    properties:
      hari_kerja:
        example:
        - Senin
        - Selasa
        - Rabu
        - Kamis
        - Jumat
        - Sabtu
        - Minggu
        items:
          type: string
        type: array
      jabatan:
        example: Anonymous
        type: string
      jam_kerja:
        items:
          $ref: '#/definitions/controller.JamKerja'
        type: array
      nama:
        example: Tes Swagger
        type: string
      phone_number:
        example: "08123456789"
        type: string
    type: object
  controller.Pasien:
    properties:
      _id:
        type: string
      alamat:
        type: string
      jenis_kelamin:
        type: string
      nama_pasien:
        type: string
      nomor_ktp:
        type: string
      nomor_telepon:
        type: string
      tanggal_lahir:
        type: string
    type: object
  controller.Poliklinik:
    properties:
      deskripsi:
        type: string
      dokter:
        $ref: '#/definitions/controller.Dokter'
      kode_poliklinik:
        description: ID               primitive.ObjectID `bson:"_id,omitempty" json:"_id,omitempty"`
        type: string
      nama_poliklinik:
        type: string
    type: object
  controller.Presensi:
    properties:
      biodata:
        $ref: '#/definitions/controller.Karyawan'
      checkin:
        description: Datetime     primitive.DateTime `bson:"datetime,omitempty" json:"datetime,omitempty"`
        example: MASUK
        type: string
      latitude:
        example: 123.11
        type: number
      location:
        example: Bandung
        type: string
      longitude:
        example: 123.11
        type: number
      phone_number:
        example: "08123456789"
        type: string
    type: object
  controller.User:
    properties:
      _id:
        type: string
      confirmpass:
        type: string
      email:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      password:
        type: string
      salt:
        type: string
    type: object
host: dimasardnt6-ulbi.herokuapp.com
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a sample swagger for Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Fiber Example API
  version: "1.0"
paths:
  /all-antrian:
    get:
      consumes:
      - application/json
      description: Mengambil semua data antrian.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Antrian'
      summary: Get All Data Antrian.
      tags:
      - Antrian
  /all-dokter:
    get:
      consumes:
      - application/json
      description: Mengambil semua data dokter.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Dokter'
      summary: Get All Data Dokter.
      tags:
      - Dokter
  /all-pasien:
    get:
      consumes:
      - application/json
      description: Mengambil semua data pasien.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Pasien'
      summary: Get All Data Pasien.
      tags:
      - Pasien
  /all-poliklinik:
    get:
      consumes:
      - application/json
      description: Mengambil semua data poliklinik.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Poliklinik'
      summary: Get All Data Poliklinik.
      tags:
      - Poliklinik
  /all-user:
    get:
      consumes:
      - application/json
      description: Mengambil semua data user.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.User'
      summary: Get All Data User.
      tags:
      - User
  /antrian/{id}:
    get:
      consumes:
      - application/json
      description: Ambil per ID data antrian.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Antrian'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get By ID Data Antrian.
      tags:
      - Antrian
  /delete/{id}:
    delete:
      consumes:
      - application/json
      description: Hapus data presensi.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Delete data presensi.
      tags:
      - Presensi
  /dokter/{id}:
    get:
      consumes:
      - application/json
      description: Ambil per ID data dokter.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Dokter'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get By ID Data Dokter.
      tags:
      - Dokter
  /ins:
    post:
      consumes:
      - application/json
      description: Input data presensi.
      parameters:
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Presensi'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Presensi'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Insert data presensi.
      tags:
      - Presensi
  /ins-antrian:
    post:
      consumes:
      - application/json
      description: Input data antrian.
      parameters:
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Antrian'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Antrian'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Insert data antrian.
      tags:
      - Antrian
  /ins-dokter:
    post:
      consumes:
      - application/json
      description: Input data dokter.
      parameters:
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Dokter'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Dokter'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Insert data dokter.
      tags:
      - Dokter
  /ins-pasien:
    post:
      consumes:
      - application/json
      description: Input data pasien.
      parameters:
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Pasien'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Pasien'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Insert data pasien.
      tags:
      - Pasien
  /ins-poliklinik:
    post:
      consumes:
      - application/json
      description: Input data poliklinik.
      parameters:
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Poliklinik'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Poliklinik'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Insert data poliklinik.
      tags:
      - Poliklinik
  /pasien/{id}:
    get:
      consumes:
      - application/json
      description: Ambil per ID data pasien.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Pasien'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get By ID Data Pasien.
      tags:
      - Pasien
  /poliklinik/{id}:
    get:
      consumes:
      - application/json
      description: Ambil per ID data poliklinik.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Poliklinik'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get By ID Data Poliklinik.
      tags:
      - Poliklinik
  /presensi:
    get:
      consumes:
      - application/json
      description: Mengambil semua data presensi.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Presensi'
      summary: Get All Data Presensi.
      tags:
      - Get All
  /presensi/{id}:
    get:
      consumes:
      - application/json
      description: Ambil per ID data presensi.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Presensi'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get By ID Data Presensi.
      tags:
      - Presensi
  /upd-antrian/{id}:
    put:
      consumes:
      - application/json
      description: Ubah data antrian.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Antrian'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Antrian'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update data antrian.
      tags:
      - Antrian
  /upd-dokter/{id}:
    put:
      consumes:
      - application/json
      description: Ubah data dokter.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Dokter'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Dokter'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update data dokter.
      tags:
      - Dokter
  /upd-pasien/{id}:
    put:
      consumes:
      - application/json
      description: Ubah data pasien.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Pasien'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Pasien'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update data pasien.
      tags:
      - Pasien
  /upd-poliklinik/{id}:
    put:
      consumes:
      - application/json
      description: Ubah data poliklinik.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Poliklinik'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Poliklinik'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update data poliklinik.
      tags:
      - Poliklinik
  /upd/{id}:
    put:
      consumes:
      - application/json
      description: Ubah data presensi.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Presensi'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Presensi'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update data presensi.
      tags:
      - Presensi
  /user/{id}:
    get:
      consumes:
      - application/json
      description: Ambil per ID data user.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.User'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get By ID Data User.
      tags:
      - User
swagger: "2.0"
